language: go

go:
  - 1.11

before_script:

install:
  - export GOPATH=$TRAVIS_BUILD_DIR/skeleton:$GOPATH
  - mkdir -p $TRAVIS_BUILD_DIR/skeleton/src/github.com
  - ln -s $TRAVIS_BUILD_DIR/skeleton/gogo/ $TRAVIS_BUILD_DIR/skeleton/src/github.com/skeleton
  - go get -v golang.org/x/time/rate
  - go get -v golang.org/x/net/context
  - go get -v github.com/dolab/colorize
  - go get -v github.com/dolab/httpdispatch
  - go get -v github.com/dolab/httptesting
  - go get -v github.com/dolab/logger

jobs:
  fast_finish: true
  include:
    - stage: go1.6
      go: 1.6
      script: go test

    - stage: go1.7
      go: 1.7
      script: go test

    - stage: go1.11
      go: 1.11
      script: go test

    - stage: latest
      go: latest
      script: go get -v github.com/dolab/gogo/cmd/gogo && gogo -h
