package templates

var (
	readmeTemplate = `# {{.Application}}

The {{.Application}} is generated by [gogo](https://github.com/dolab/gogo) command.

### Development

<bash>
$ # show gogo helps
$ gogo -h

$ # create a new application
$ gogo new {{.Application}}

$ # resolve dependences
$ cd {{.Application}}/gogo
$ make

$ # generate controller
$ # NOTE: you should update application.go and add app.Resource("/user", User) route by hand
$ gogo g c user

$ # generate filter
$ gogo g f session

$ # generate model
$ gogo g m user

$ # run test
$ make

$ # run development server
$ make godev
</bash>

### Custom Server

You can custom Server by implementing interfaces following:

<golang>
// A RequestReceivedInterceptor represents request received hook interface of server
type RequestReceivedInterceptor interface {
	RequestReceived() []interceptors.Interceptor
}

// A RequestRoutedInterceptor represents request routed hook interface of server
type RequestRoutedInterceptor interface {
	RequestRouted() []interceptors.Interceptor
}

// A ResponseReadyInterceptor represents response ready for sending data hook interface of server
type ResponseReadyInterceptor interface {
	ResponseReady() []interceptors.Interceptor
}

// A ResponseAlwaysInterceptor represents response routed success hook interface of server
type ResponseAlwaysInterceptor interface {
	ResponseAlways() []interceptors.Interceptor
}
</golang>

### APP Struct

<bash>
my
├── app                # workdir
│   ├── controllers    # biz
│   ├── middlewares    # custom filters of gogo
│   ├── models         # data driver
│   └── protos         # protobuf
├── bin                # go build output of make gopackage
├── config             # config
├── gogo               # auto generated dirs of gogo
│   └── errors         # auto generated errors from gogo
│   └── pbs            # auto generated protobufs
│   └── services       # auto generated services from protobuf
├── log                # default log output
└── tmp                # tmpdirs
    ├── cache          # file cache
    ├── pids           # run pid if required
    └── sockets        # run socket if required
</bash>
`
)
